 # Copyright 2016 Igor Rubis
 # Licensed under the Apache License, Version 2.0

Vagrant.configure(2) do |config|
    config.vm.box = "hashicorp/precise64"

    config.vm.network "forwarded_port", guest: 80, host: 8080       # apache default port
    config.vm.network "forwarded_port", guest: 8080, host: 8081     # Jenkins port
    config.vm.network "forwarded_port", guest: 4444, host: 4444     # selenium grid port

    config.vm.provider "virtualbox" do |v|
        v.name = "my_vm"
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.provision :shell, path: "scripts/install_and_set_up_java.sh"

    config.vm.provision :shell, path: "scripts/install_and_set_up_apache.sh"

    config.vm.provision :shell, path: "scripts/install_and_set_up_jenkins.sh"

    config.vm.provision :shell, path: "scripts/install_and_set_up_selenium-grid.sh"

    config.vm.provision :shell, path: "scripts/install_and_set_up_docker.sh"
end